name: muviee
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  shared_preferences: ^2.0.20
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  injectable: ^2.1.0
  get_it: ^7.2.0
  build_runner: ^2.3.3
  pin_code_fields: ^7.4.0
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  simple_mapper: ^1.2.0
  json_serializable: ^6.6.1
  smooth_page_indicator: ^1.0.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  video_player: ^2.6.1
  lottie: ^2.3.2
  intl: ^0.17.0
  visibility_detector: ^0.4.0+2
  loadmore_listview: ^1.0.7
  photo_view: ^0.14.0
  timeago: ^3.3.0
  external_path: ^1.0.3
  permission_handler: ^10.2.0
  path_provider: ^2.0.14



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.0



flutter_native_splash:
  color: "#FF0040"
  color_dark: "#FF0040"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    icon_background_color: "#FF0040"
    image: assets/images/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"
  adaptive_icon_background: "#FF0040"
  android_rounded_corners: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/lotties/
    - assets/jsons/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf-pro-Regular.ttf
