import 'r.dart';

final enLang = {
  R.login: "Login",
  R.sign_out: "Sign out",
  R.sign_up: "Sign up",
  R.neverMissMovies: "Never miss \nnew movies & series",
  R.beTheFirstOne: "Be the first one to watch the latest movies and series on Muviee",
  R.getStarted: "Get Started",
  R.password: "password",
  R.email: "email",
  R.forgotPassword: "Forgot password?",
  R.confirmPassword: "confirm password",
  R.confirm: "Confirm",
  R.alreadyhaveanaccount: "Already have an account? ",
  R.wehavesentaverificationcode: "We have sent a 5-digits verification code to your email",
  R.didntseeanycode: "Didn't see any code? ",
  R.back: "Back",
  R.onlyafewstepleft: "Only a few steps left to start using Muviee",
  R.nickname: "nickname",
  R.country: "country",
  R.logininstead: "Login instead?",
  R.recoveraccount: "Recover account",
  R.setnewpassword: "Set new password",
  R.latest: "Latest",
  R.seeAll: "See all",
  R.popular: "Popular",
  R.topRated: "Top Rated",
  R.story: "Story",
  R.more: "More",
  R.less: "Less",
  R.cast: "Cast",
  R.preview: "Preview",
  R.review: "Review",
  R.profile: "Profile",
  R.youractivities: "Your activities",
  R.saved: "Saved",
  R.history: "History",
  R.account: "Account",
  R.settings: "Settings",
  R.changePassword: "Change password",
  R.general: "General",
  R.language: "Language",
  R.darkMode: "Dark mode",
  R.home: "Home",
  R.search: "Search",
  R.watching: "Watching",
  R.options: "Options",
  R.share: "Share",
  R.download: "Download",
  R.movie: "Movie",
  R.actor: "Actor",
  R.bio: "Bio",
  R.year: "Year",
  R.filter: "Filter",
  R.selectCountry: "Select country",
  R.searchSomething: "Search something",
  R.like: "Like",
  R.savedToFavorite: "Saved to favorite movies",
  R.removedFromFavorite: "Removed from favorite movies",
  R.letsaveyourfirstmovie: "Let's save your first movie",
  R.loadingMovie: "Loading movie...",
  R.getMovieFailed: "Get movie failed",
  R.passwordMustAtLeast6char: "Password must at least 6 character",
  R.passwordsDoNotMatch: "Passwords do not match",
  R.invalidEmailAddress: "Invalid email address",
  R.pleaseFillAllTheFields: "Please fill all the fields",
  R.greatJob: "Great job",
  R.letswatchyourfirstmovie: "Let's watch your first movie on ",
  R.youhaventwatchedanymovieyet: "You haven't watched any movie yet",
  R.youhaventreviewedanymovieyet: "You haven't reviewed any movie yet",
};
