import 'r.dart';

final viLang = {
  R.login: "Đăng nhập",
  R.sign_out: "Đăng xuất",
  R.sign_up: "Đăng ký",
  R.neverMissMovies: "Đừng bỏ lỡ \nnhững thước phim nổi bật",
  R.beTheFirstOne: "Trở thành người đầu tiên xem phim nóng hổi trên Muviee",
  R.getStarted: "Bắt Đầu",
  R.password: "mật khẩu",
  R.email: "email",
  R.forgotPassword: "Quên mật khẩu?",
  R.confirmPassword: "xác nhận mật khẩu",
  R.confirm: "Xác nhận",
  R.alreadyhaveanaccount: "Đã có tài khoản? ",
  R.wehavesentaverificationcode: "Chúng tôi vừa gửi mã gồm 5 ký tự đến email của bạn",
  R.didntseeanycode: "Không nhận được mã? ",
  R.back: "Trở về",
  R.onlyafewstepleft: "Vài bước nữa thôi để trải nghiệm Muviee",
  R.nickname: "biệt danh",
  R.country: "quốc gia",
  R.logininstead: "Đăng nhập nhé?",
  R.recoveraccount: "Khôi phục tài khoản",
  R.setnewpassword: "Đặt lại mật khẩu",
  R.latest: "Mới nhất",
  R.seeAll: "Tất cả",
  R.popular: "Nổi bật",
  R.topRated: "Xếp hạng",
  R.story: "Bối cảnh",
  R.more: "Thêm",
  R.less: "Bớt",
  R.cast: "Diễn viên",
  R.preview: "Xem trước",
  R.review: "Đánh giá",
  R.profile: "Hồ sơ",
  R.youractivities: "Hoạt động",
  R.saved: "Đã lưu",
  R.history: "Lịch sử",
  R.account: "Tài khoản",
  R.settings: "Cài đặt",
  R.changePassword: "Đổi mật khẩu",
  R.general: "Chung",
  R.language: "Ngôn ngữ",
  R.darkMode: "Chế độ tối",
  R.home: "Trang chủ",
  R.search: "Tìm kiếm",
  R.watching: "Xem",
  R.options: "Tuỳ chọn",
  R.share: "Chia sẻ",
  R.download: "Tải xuống",
  R.movie: "Phim",
  R.actor: "Diễn viên",
  R.bio: "Tiểu sử",
  R.year: "Năm",
  R.filter: "Bộ lọc",
  R.selectCountry: "Chọn quốc gia",
  R.searchSomething: "Tìm kiếm gì đó",
  R.like: "Thích",
  R.savedToFavorite: "Đã lưu vào yêu thích",
  R.removedFromFavorite: "Đã xoá khỏi yêu thích",
  R.letsaveyourfirstmovie: "Lưu bộ phim đầu tiên đi nhé",
  R.loadingMovie: "Tải phim...",
  R.getMovieFailed: "Tải phim thất bại",
  R.passwordMustAtLeast6char: "Mật khẩu tối thiểu 6 ký tự",
  R.passwordsDoNotMatch: "Mật khẩu không khớp",
  R.invalidEmailAddress: "Tài khoản email không hợp lệ",
  R.pleaseFillAllTheFields: "Vui lòng điền đủ thông tin",
  R.greatJob: "Tuyệt vời",
  R.letswatchyourfirstmovie: "Bắt đầu xem phim ngay trên ",
  R.youhaventwatchedanymovieyet: "Bạn chưa xem phim nào cả",
  R.youhaventreviewedanymovieyet: "Bạn chưa đánh giá phim nào cả",
  R.warning: "Cảnh báo",
  R.areyousurewanttodeletethismovie: 'Bạn có chắc muốn xoá phim này?',
  R.no: 'Không',
  R.yes: 'Có',
  R.placeAComment: 'Để lại bình luận',
  R.yourComment: 'Bình luận của bạn',
  R.submit: "Gửi",
  R.submittedSuccessfully: "Gửi đi thành công",
  R.areyousureyouwanttodeletethisreview: "Bạn có chắc muốn xoá bình luận này?",
  R.editComment: "Sửa bình luận",
  R.similar: "Tương tự",
  R.currentPass: "mật khẩu hiện tại",
  R.newPass: "mật khẩu mới",
  R.changePassSuccess: "Đổi mật khẩu thành công",
};
